﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Using_SQL_Inbuld_Model
{
    public partial class PredictEmployeeLogInTime
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"EmployeeID", @"EmployeeID"),new InputOutputColumnPair(@"EndTime", @"EndTime")})      
                                    .Append(mlContext.Transforms.Conversion.ConvertType(@"LoginDate", @"LoginDate"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"EmployeeID",@"EndTime",@"LoginDate"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=26,NumberOfIterations=4,MinimumExampleCountPerLeaf=20,LearningRate=0.10726258019889,LabelColumnName=@"StartTime",FeatureColumnName=@"Features",ExampleWeightColumnName=null,Booster=new GradientBooster.Options(){SubsampleFraction=0.999999776672986,FeatureFraction=0.99999999,L1Regularization=3.55466288954644E-07,L2Regularization=0.309025130817048},MaximumBinCountPerFeature=516}));

            return pipeline;
        }
    }
}
