// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Using_SQL_Inbuld_Model
{
    public partial class PredictEmployeeLogInTime
    {
        /// <summary>
        /// model input class for PredictEmployeeLogInTime.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"EmployeeID")]
            public float EmployeeID { get; set; }

            [ColumnName(@"LoginDate")]
            public DateTime LoginDate { get; set; }

            [ColumnName(@"StartTime")]
            public float StartTime { get; set; }

            [ColumnName(@"EndTime")]
            public float EndTime { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for PredictEmployeeLogInTime.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"EmployeeID")]
            public float EmployeeID { get; set; }

            [ColumnName(@"LoginDate")]
            public float LoginDate { get; set; }

            [ColumnName(@"StartTime")]
            public float StartTime { get; set; }

            [ColumnName(@"EndTime")]
            public float EndTime { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("PredictEmployeeLogInTime.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();

            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
